apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    version: 58.3.0
    releaseName: monitoring
    namespace: monitoring
    valuesFile: prometheus-grafana.yaml
resources:
  - namespace.yaml
